apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app
spec:
  replicas: 2
  selector:
    matchLabels:
      name: sample-app
  template:
    metadata:
      labels:
        name: sample-app
    spec:
      containers:
      - name: sample-app
        image: saichandu5/sample-app
        ports:
          - containerPort: 9090
